---
# tasks file for win_service_config

- name: Install openssh
  win_chocolatey:
    name: "{{package_name}}"
    params: "{{parameters}}"
    state: present
  when: 
    ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
 
- name: Start windows service
  win_service:
    name: "{{service_name}}"
    start_mode: auto
    state: started
  when: 
    ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: Creating firewall rule
  win_firewall_rule: 
    name: "{{service_name}}"
    localport: "{{local_port}}"
    action: allow
    direction: in
    protocol: "{{protocol_name}}"
    state: present
    enabled: yes
