---
# tasks file for win_add_user

- name: Add user 
  win_domain_user:
    name: "{{item.name}}"
    firstname: "{{item.firstname}}"
    surname: "{{item.surname}}"
    password: "{{item.password}}"
    email: "{{item.email}}"
    state: present
  with_items:
  - "{{user_info}}"
